Website_main_App/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView

from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from accounts.views import SignUpView, FarmerSignUpView, CustomerSignUpView, FarmerSignUpView, CustomerSignUpView, LoginView, guest_register_view
from products.views import AddProductView3, FarmerListView
# LoginView, RegisterView

from .views import home_page
from predict.views import predictshow,SalesAjaxView

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
    # url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^signup/farmer$', FarmerSignUpView.as_view(), name='farmer_signup'),
    url(r'^signup/customer$', CustomerSignUpView.as_view(), name='customer_signup'),
    url(r'^add-product$', AddProductView3.as_view(), name='add_product'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^my-products$', FarmerListView.as_view(), name='my_product'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include("search.urls", namespace='search')),
    # url(r'^predict/(?P<pk>\d+)/$',predictshow,name='predict'),
    url(r'^predict/$',predictshow,name='predictnoid'),
    url(r'^predict/api/(?P<pk>\d+)/$',SalesAjaxView.as_view(),name='predict-data'),
    url(r'^contact/', include("contact.urls", namespace='contact')),
]

if settings.DEBUG:
	urlpatterns =urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns =urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update, 
        checkout_home,
        checkout_done_view
        )

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
]

contact/urls.py
from django.conf.urls import url

from .views import (
        ContactView,
        )

urlpatterns = [
    url(r'^$', ContactView.as_view(), name='message'),
]

products/urls.py
from django.conf.urls import url

from .views import (
        ProductListView,
        ProductDetailSlugView,
        ProductEditView,
        ProductDeleteView
        # , 
        # ProductDownloadView
        )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit-product$', ProductEditView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete-product$', ProductDeleteView.as_view(), name='delete'),
    # url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/$', ProductDownloadView.as_view(), name='download'),
]

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

<!-- Fontawesome CSS -->

<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

<!-- jquery-confirm CSS -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">


<!-- Custom Stripe Styling -->

<!-- <link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}"> -->

templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS
slim is missing ajax -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

<!-- Stripe JS -->
<script src="https://js.stripe.com/v3/"></script>


<!-- jquery-confirm JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<!-- js Render -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.88/jsrender.min.js'></script>
{% include 'base/js_templates.html' %}


<!-- Chart.js -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.js"></script>


<!-- Django Secure AJAX JS -->

<!-- <script src='{% static "js/csrf.ajax.js" %}'></script> -->

<!-- eCommerce Sales Data JS -->

<!-- <script src='{% static "js/ecommerce.sales.js" %}'></script>
 -->

<!-- eCommerce Custom JS -->

<!-- <script src='{% static "js/ecommerce.js" %}'></script> -->


<!-- eCommerce Main JS -->

<!-- <script src='{% static "js/ecommerce.main.js" %}'></script>  -->

templates/base/js_templates.html
{% verbatim %}
<!-- stripe template form -->
<script id="stripeTemplate" type="text/x-jsrender">
    <form class='payment-form' action="" method="post" id="payment-form" data-token='{{:publishKey}}' data-next-url='{{:nextUrl}}'>
  <div class="form-row">
    <!-- <label for="card-element">
      Credit or debit card
    </label> -->
    <div id="card-element" class='form-control'> 
      <!-- a Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button class='btn btn-primary my-3 btn-load'>{{:btnTitle }}</button>

    </form>

</script>
{% endverbatim %}

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'signup' as register_url %}
{% url 'products:list' as product_url %}
{% url 'add_product' as add_url %}
{% url 'my_product' as myproduct_url %}
{% url 'cart:home' as cart_url %}
{% url 'predictnoid' as predict_url %}
{% url 'contact:message' as contact_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
   <div class='container'>
  <a class="navbar-brand" href="{{ home_url }}">
    <img src="//getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    AGRI MART BUY AND SELL
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == product_url %}active{% endif %}">
        <a class="nav-link" href="{{ product_url }}">Products</a>
      </li>
      <li class="nav-item {% if request.path == predict_url %}active{% endif %}">
        <a class="nav-link" href="{{ predict_url }}">Forecast graph</a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{contact_url}}">Contact</a>
      </li>

      {% if request.user.is_authenticated and request.user.is_farmer %}
      <li class="nav-item {% if request.path == add_url %}active{% endif %}">
        <a class="nav-link" href="{{ add_url }}">Add Product</a>
      </li>
      {% endif %}


      {% if request.user.is_authenticated %}
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="#">Me: {{request.user}}</a>
        {% if request.user.is_farmer %}
          <a class="dropdown-item" href="{{ myproduct_url }}">My Products</a>
          
        {% endif %}

          <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
        </div>
        
      </li>
      {% else %}
       <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}"><span class='navbar-cart-count'>{{ request.session.cart_items }}</span> <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>


    </ul>
   {%include 'search/snippets/search-form.html' %}
  </div>
</div>
</nav>